/* Bsw_MemMap.h for AUTOSAR Memory Mapping R4.0 Rev 3 */
/* MISRA RULE 19.15 VIOLATION: MemMap header concept - no protection against repeated inclusion intended */


#if 0  // to start with #elif

/* VARIABLES */
#elif defined BSW_START_SEC_VAR_NO_INIT_BOOLEAN
    #undef  BSW_START_SEC_VAR_NO_INIT_BOOLEAN
    /* NOTE: As per BSW coding guidelines the init policy NO_INIT shall not be used. */

#elif defined BSW_STOP_SEC_VAR_NO_INIT_BOOLEAN
    #undef BSW_STOP_SEC_VAR_NO_INIT_BOOLEAN



#elif defined BSW_START_SEC_VAR_NO_INIT_8
    #undef  BSW_START_SEC_VAR_NO_INIT_8
    /* NOTE: As per BSW coding guidelines the init policy NO_INIT shall not be used. */

#elif defined BSW_STOP_SEC_VAR_NO_INIT_8
    #undef BSW_STOP_SEC_VAR_NO_INIT_8



#elif defined BSW_START_SEC_VAR_NO_INIT_16
    #undef  BSW_START_SEC_VAR_NO_INIT_16
    /* NOTE: As per BSW coding guidelines the init policy NO_INIT shall not be used. */

#elif defined BSW_STOP_SEC_VAR_NO_INIT_16
    #undef BSW_STOP_SEC_VAR_NO_INIT_16



#elif defined BSW_START_SEC_VAR_NO_INIT_32
    #undef  BSW_START_SEC_VAR_NO_INIT_32
    /* NOTE: As per BSW coding guidelines the init policy NO_INIT shall not be used. */

#elif defined BSW_STOP_SEC_VAR_NO_INIT_32
    #undef BSW_STOP_SEC_VAR_NO_INIT_32



#elif defined BSW_START_SEC_VAR_NO_INIT_UNSPECIFIED
    #undef  BSW_START_SEC_VAR_NO_INIT_UNSPECIFIED
    /* NOTE: As per BSW coding guidelines the init policy NO_INIT shall not be used. */

#elif defined BSW_STOP_SEC_VAR_NO_INIT_UNSPECIFIED
    #undef BSW_STOP_SEC_VAR_NO_INIT_UNSPECIFIED



#elif defined BSW_START_SEC_VAR_CLEARED_BOOLEAN
    #undef  BSW_START_SEC_VAR_CLEARED_BOOLEAN

#elif defined BSW_STOP_SEC_VAR_CLEARED_BOOLEAN
    #undef BSW_STOP_SEC_VAR_CLEARED_BOOLEAN



#elif defined BSW_START_SEC_VAR_CLEARED_8
    #undef  BSW_START_SEC_VAR_CLEARED_8

#elif defined BSW_STOP_SEC_VAR_CLEARED_8
    #undef BSW_STOP_SEC_VAR_CLEARED_8



#elif defined BSW_START_SEC_VAR_CLEARED_16
    #undef  BSW_START_SEC_VAR_CLEARED_16

#elif defined BSW_STOP_SEC_VAR_CLEARED_16
    #undef BSW_STOP_SEC_VAR_CLEARED_16



#elif defined BSW_START_SEC_VAR_CLEARED_32
    #undef  BSW_START_SEC_VAR_CLEARED_32

#elif defined BSW_STOP_SEC_VAR_CLEARED_32
    #undef BSW_STOP_SEC_VAR_CLEARED_32



#elif defined BSW_START_SEC_VAR_CLEARED_UNSPECIFIED
    #undef  BSW_START_SEC_VAR_CLEARED_UNSPECIFIED

#elif defined BSW_STOP_SEC_VAR_CLEARED_UNSPECIFIED
    #undef BSW_STOP_SEC_VAR_CLEARED_UNSPECIFIED



#elif defined BSW_START_SEC_VAR_POWER_ON_CLEARED_BOOLEAN
    #undef  BSW_START_SEC_VAR_POWER_ON_CLEARED_BOOLEAN

#elif defined BSW_STOP_SEC_VAR_POWER_ON_CLEARED_BOOLEAN
    #undef BSW_STOP_SEC_VAR_POWER_ON_CLEARED_BOOLEAN



#elif defined BSW_START_SEC_VAR_POWER_ON_CLEARED_8
    #undef  BSW_START_SEC_VAR_POWER_ON_CLEARED_8

#elif defined BSW_STOP_SEC_VAR_POWER_ON_CLEARED_8
    #undef BSW_STOP_SEC_VAR_POWER_ON_CLEARED_8



#elif defined BSW_START_SEC_VAR_POWER_ON_CLEARED_16
    #undef  BSW_START_SEC_VAR_POWER_ON_CLEARED_16

#elif defined BSW_STOP_SEC_VAR_POWER_ON_CLEARED_16
    #undef BSW_STOP_SEC_VAR_POWER_ON_CLEARED_16



#elif defined BSW_START_SEC_VAR_POWER_ON_CLEARED_32
    #undef  BSW_START_SEC_VAR_POWER_ON_CLEARED_32

#elif defined BSW_STOP_SEC_VAR_POWER_ON_CLEARED_32
    #undef BSW_STOP_SEC_VAR_POWER_ON_CLEARED_32



#elif defined BSW_START_SEC_VAR_POWER_ON_CLEARED_UNSPECIFIED
    #undef  BSW_START_SEC_VAR_POWER_ON_CLEARED_UNSPECIFIED

#elif defined BSW_STOP_SEC_VAR_POWER_ON_CLEARED_UNSPECIFIED
    #undef BSW_STOP_SEC_VAR_POWER_ON_CLEARED_UNSPECIFIED



#elif defined BSW_START_SEC_VAR_INIT_BOOLEAN
    #undef  BSW_START_SEC_VAR_INIT_BOOLEAN

#elif defined BSW_STOP_SEC_VAR_INIT_BOOLEAN
    #undef BSW_STOP_SEC_VAR_INIT_BOOLEAN



#elif defined BSW_START_SEC_VAR_INIT_8
    #undef  BSW_START_SEC_VAR_INIT_8

#elif defined BSW_STOP_SEC_VAR_INIT_8
    #undef BSW_STOP_SEC_VAR_INIT_8



#elif defined BSW_START_SEC_VAR_INIT_16
    #undef  BSW_START_SEC_VAR_INIT_16

#elif defined BSW_STOP_SEC_VAR_INIT_16
    #undef BSW_STOP_SEC_VAR_INIT_16



#elif defined BSW_START_SEC_VAR_INIT_32
    #undef  BSW_START_SEC_VAR_INIT_32

#elif defined BSW_STOP_SEC_VAR_INIT_32
    #undef BSW_STOP_SEC_VAR_INIT_32



#elif defined BSW_START_SEC_VAR_INIT_UNSPECIFIED
    #undef  BSW_START_SEC_VAR_INIT_UNSPECIFIED

#elif defined BSW_STOP_SEC_VAR_INIT_UNSPECIFIED
    #undef BSW_STOP_SEC_VAR_INIT_UNSPECIFIED



#elif defined BSW_START_SEC_VAR_POWER_ON_INIT_BOOLEAN
    #undef  BSW_START_SEC_VAR_POWER_ON_INIT_BOOLEAN

#elif defined BSW_STOP_SEC_VAR_POWER_ON_INIT_BOOLEAN
    #undef BSW_STOP_SEC_VAR_POWER_ON_INIT_BOOLEAN



#elif defined BSW_START_SEC_VAR_POWER_ON_INIT_8
    #undef  BSW_START_SEC_VAR_POWER_ON_INIT_8

#elif defined BSW_STOP_SEC_VAR_POWER_ON_INIT_8
    #undef BSW_STOP_SEC_VAR_POWER_ON_INIT_8



#elif defined BSW_START_SEC_VAR_POWER_ON_INIT_16
    #undef  BSW_START_SEC_VAR_POWER_ON_INIT_16

#elif defined BSW_STOP_SEC_VAR_POWER_ON_INIT_16
    #undef BSW_STOP_SEC_VAR_POWER_ON_INIT_16



#elif defined BSW_START_SEC_VAR_POWER_ON_INIT_32
    #undef  BSW_START_SEC_VAR_POWER_ON_INIT_32

#elif defined BSW_STOP_SEC_VAR_POWER_ON_INIT_32
    #undef BSW_STOP_SEC_VAR_POWER_ON_INIT_32



#elif defined BSW_START_SEC_VAR_POWER_ON_INIT_UNSPECIFIED
    #undef  BSW_START_SEC_VAR_POWER_ON_INIT_UNSPECIFIED

#elif defined BSW_STOP_SEC_VAR_POWER_ON_INIT_UNSPECIFIED
    #undef BSW_STOP_SEC_VAR_POWER_ON_INIT_UNSPECIFIED



#elif defined BSW_START_SEC_VAR_FAST_NO_INIT_BOOLEAN
    #undef  BSW_START_SEC_VAR_FAST_NO_INIT_BOOLEAN
    /* NOTE: As per BSW coding guidelines the init policy NO_INIT shall not be used. */

#elif defined BSW_STOP_SEC_VAR_FAST_NO_INIT_BOOLEAN
    #undef BSW_STOP_SEC_VAR_FAST_NO_INIT_BOOLEAN



#elif defined BSW_START_SEC_VAR_FAST_NO_INIT_8
    #undef  BSW_START_SEC_VAR_FAST_NO_INIT_8
    /* NOTE: As per BSW coding guidelines the init policy NO_INIT shall not be used. */

#elif defined BSW_STOP_SEC_VAR_FAST_NO_INIT_8
    #undef BSW_STOP_SEC_VAR_FAST_NO_INIT_8



#elif defined BSW_START_SEC_VAR_FAST_NO_INIT_16
    #undef  BSW_START_SEC_VAR_FAST_NO_INIT_16
    /* NOTE: As per BSW coding guidelines the init policy NO_INIT shall not be used. */

#elif defined BSW_STOP_SEC_VAR_FAST_NO_INIT_16
    #undef BSW_STOP_SEC_VAR_FAST_NO_INIT_16



#elif defined BSW_START_SEC_VAR_FAST_NO_INIT_32
    #undef  BSW_START_SEC_VAR_FAST_NO_INIT_32
    /* NOTE: As per BSW coding guidelines the init policy NO_INIT shall not be used. */

#elif defined BSW_STOP_SEC_VAR_FAST_NO_INIT_32
    #undef BSW_STOP_SEC_VAR_FAST_NO_INIT_32



#elif defined BSW_START_SEC_VAR_FAST_NO_INIT_UNSPECIFIED
    #undef  BSW_START_SEC_VAR_FAST_NO_INIT_UNSPECIFIED
    /* NOTE: As per BSW coding guidelines the init policy NO_INIT shall not be used. */

#elif defined BSW_STOP_SEC_VAR_FAST_NO_INIT_UNSPECIFIED
    #undef BSW_STOP_SEC_VAR_FAST_NO_INIT_UNSPECIFIED



#elif defined BSW_START_SEC_VAR_FAST_CLEARED_BOOLEAN
    #undef  BSW_START_SEC_VAR_FAST_CLEARED_BOOLEAN

#elif defined BSW_STOP_SEC_VAR_FAST_CLEARED_BOOLEAN
    #undef BSW_STOP_SEC_VAR_FAST_CLEARED_BOOLEAN



#elif defined BSW_START_SEC_VAR_FAST_CLEARED_8
    #undef  BSW_START_SEC_VAR_FAST_CLEARED_8

#elif defined BSW_STOP_SEC_VAR_FAST_CLEARED_8
    #undef BSW_STOP_SEC_VAR_FAST_CLEARED_8



#elif defined BSW_START_SEC_VAR_FAST_CLEARED_16
    #undef  BSW_START_SEC_VAR_FAST_CLEARED_16

#elif defined BSW_STOP_SEC_VAR_FAST_CLEARED_16
    #undef BSW_STOP_SEC_VAR_FAST_CLEARED_16



#elif defined BSW_START_SEC_VAR_FAST_CLEARED_32
    #undef  BSW_START_SEC_VAR_FAST_CLEARED_32

#elif defined BSW_STOP_SEC_VAR_FAST_CLEARED_32
    #undef BSW_STOP_SEC_VAR_FAST_CLEARED_32



#elif defined BSW_START_SEC_VAR_FAST_CLEARED_UNSPECIFIED
    #undef  BSW_START_SEC_VAR_FAST_CLEARED_UNSPECIFIED

#elif defined BSW_STOP_SEC_VAR_FAST_CLEARED_UNSPECIFIED
    #undef BSW_STOP_SEC_VAR_FAST_CLEARED_UNSPECIFIED



#elif defined BSW_START_SEC_VAR_FAST_POWER_ON_CLEARED_BOOLEAN
    #undef  BSW_START_SEC_VAR_FAST_POWER_ON_CLEARED_BOOLEAN

#elif defined BSW_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_BOOLEAN
    #undef BSW_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_BOOLEAN



#elif defined BSW_START_SEC_VAR_FAST_POWER_ON_CLEARED_8
    #undef  BSW_START_SEC_VAR_FAST_POWER_ON_CLEARED_8

#elif defined BSW_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_8
    #undef BSW_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_8



#elif defined BSW_START_SEC_VAR_FAST_POWER_ON_CLEARED_16
    #undef  BSW_START_SEC_VAR_FAST_POWER_ON_CLEARED_16

#elif defined BSW_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_16
    #undef BSW_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_16



#elif defined BSW_START_SEC_VAR_FAST_POWER_ON_CLEARED_32
    #undef  BSW_START_SEC_VAR_FAST_POWER_ON_CLEARED_32

#elif defined BSW_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_32
    #undef BSW_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_32



#elif defined BSW_START_SEC_VAR_FAST_POWER_ON_CLEARED_UNSPECIFIED
    #undef  BSW_START_SEC_VAR_FAST_POWER_ON_CLEARED_UNSPECIFIED

#elif defined BSW_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_UNSPECIFIED
    #undef BSW_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_UNSPECIFIED



#elif defined BSW_START_SEC_VAR_FAST_INIT_BOOLEAN
    #undef  BSW_START_SEC_VAR_FAST_INIT_BOOLEAN

#elif defined BSW_STOP_SEC_VAR_FAST_INIT_BOOLEAN
    #undef BSW_STOP_SEC_VAR_FAST_INIT_BOOLEAN



#elif defined BSW_START_SEC_VAR_FAST_INIT_8
    #undef  BSW_START_SEC_VAR_FAST_INIT_8

#elif defined BSW_STOP_SEC_VAR_FAST_INIT_8
    #undef BSW_STOP_SEC_VAR_FAST_INIT_8



#elif defined BSW_START_SEC_VAR_FAST_INIT_16
    #undef  BSW_START_SEC_VAR_FAST_INIT_16

#elif defined BSW_STOP_SEC_VAR_FAST_INIT_16
    #undef BSW_STOP_SEC_VAR_FAST_INIT_16



#elif defined BSW_START_SEC_VAR_FAST_INIT_32
    #undef  BSW_START_SEC_VAR_FAST_INIT_32

#elif defined BSW_STOP_SEC_VAR_FAST_INIT_32
    #undef BSW_STOP_SEC_VAR_FAST_INIT_32



#elif defined BSW_START_SEC_VAR_FAST_INIT_UNSPECIFIED
    #undef  BSW_START_SEC_VAR_FAST_INIT_UNSPECIFIED

#elif defined BSW_STOP_SEC_VAR_FAST_INIT_UNSPECIFIED
    #undef BSW_STOP_SEC_VAR_FAST_INIT_UNSPECIFIED



#elif defined BSW_START_SEC_VAR_FAST_POWER_ON_INIT_BOOLEAN
    #undef  BSW_START_SEC_VAR_FAST_POWER_ON_INIT_BOOLEAN

#elif defined BSW_STOP_SEC_VAR_FAST_POWER_ON_INIT_BOOLEAN
    #undef BSW_STOP_SEC_VAR_FAST_POWER_ON_INIT_BOOLEAN



#elif defined BSW_START_SEC_VAR_FAST_POWER_ON_INIT_8
    #undef  BSW_START_SEC_VAR_FAST_POWER_ON_INIT_8

#elif defined BSW_STOP_SEC_VAR_FAST_POWER_ON_INIT_8
    #undef BSW_STOP_SEC_VAR_FAST_POWER_ON_INIT_8



#elif defined BSW_START_SEC_VAR_FAST_POWER_ON_INIT_16
    #undef  BSW_START_SEC_VAR_FAST_POWER_ON_INIT_16

#elif defined BSW_STOP_SEC_VAR_FAST_POWER_ON_INIT_16
    #undef BSW_STOP_SEC_VAR_FAST_POWER_ON_INIT_16



#elif defined BSW_START_SEC_VAR_FAST_POWER_ON_INIT_32
    #undef  BSW_START_SEC_VAR_FAST_POWER_ON_INIT_32

#elif defined BSW_STOP_SEC_VAR_FAST_POWER_ON_INIT_32
    #undef BSW_STOP_SEC_VAR_FAST_POWER_ON_INIT_32



#elif defined BSW_START_SEC_VAR_FAST_POWER_ON_INIT_UNSPECIFIED
    #undef  BSW_START_SEC_VAR_FAST_POWER_ON_INIT_UNSPECIFIED

#elif defined BSW_STOP_SEC_VAR_FAST_POWER_ON_INIT_UNSPECIFIED
    #undef BSW_STOP_SEC_VAR_FAST_POWER_ON_INIT_UNSPECIFIED



#elif defined BSW_START_SEC_VAR_SLOW_NO_INIT_BOOLEAN
    #undef  BSW_START_SEC_VAR_SLOW_NO_INIT_BOOLEAN
    /* NOTE: As per BSW coding guidelines the init policy NO_INIT shall not be used. */

#elif defined BSW_STOP_SEC_VAR_SLOW_NO_INIT_BOOLEAN
    #undef BSW_STOP_SEC_VAR_SLOW_NO_INIT_BOOLEAN



#elif defined BSW_START_SEC_VAR_SLOW_NO_INIT_8
    #undef  BSW_START_SEC_VAR_SLOW_NO_INIT_8
    /* NOTE: As per BSW coding guidelines the init policy NO_INIT shall not be used. */

#elif defined BSW_STOP_SEC_VAR_SLOW_NO_INIT_8
    #undef BSW_STOP_SEC_VAR_SLOW_NO_INIT_8



#elif defined BSW_START_SEC_VAR_SLOW_NO_INIT_16
    #undef  BSW_START_SEC_VAR_SLOW_NO_INIT_16
    /* NOTE: As per BSW coding guidelines the init policy NO_INIT shall not be used. */

#elif defined BSW_STOP_SEC_VAR_SLOW_NO_INIT_16
    #undef BSW_STOP_SEC_VAR_SLOW_NO_INIT_16



#elif defined BSW_START_SEC_VAR_SLOW_NO_INIT_32
    #undef  BSW_START_SEC_VAR_SLOW_NO_INIT_32
    /* NOTE: As per BSW coding guidelines the init policy NO_INIT shall not be used. */

#elif defined BSW_STOP_SEC_VAR_SLOW_NO_INIT_32
    #undef BSW_STOP_SEC_VAR_SLOW_NO_INIT_32



#elif defined BSW_START_SEC_VAR_SLOW_NO_INIT_UNSPECIFIED
    #undef  BSW_START_SEC_VAR_SLOW_NO_INIT_UNSPECIFIED
    /* NOTE: As per BSW coding guidelines the init policy NO_INIT shall not be used. */

#elif defined BSW_STOP_SEC_VAR_SLOW_NO_INIT_UNSPECIFIED
    #undef BSW_STOP_SEC_VAR_SLOW_NO_INIT_UNSPECIFIED



#elif defined BSW_START_SEC_VAR_SLOW_CLEARED_BOOLEAN
    #undef  BSW_START_SEC_VAR_SLOW_CLEARED_BOOLEAN

#elif defined BSW_STOP_SEC_VAR_SLOW_CLEARED_BOOLEAN
    #undef BSW_STOP_SEC_VAR_SLOW_CLEARED_BOOLEAN



#elif defined BSW_START_SEC_VAR_SLOW_CLEARED_8
    #undef  BSW_START_SEC_VAR_SLOW_CLEARED_8

#elif defined BSW_STOP_SEC_VAR_SLOW_CLEARED_8
    #undef BSW_STOP_SEC_VAR_SLOW_CLEARED_8



#elif defined BSW_START_SEC_VAR_SLOW_CLEARED_16
    #undef  BSW_START_SEC_VAR_SLOW_CLEARED_16

#elif defined BSW_STOP_SEC_VAR_SLOW_CLEARED_16
    #undef BSW_STOP_SEC_VAR_SLOW_CLEARED_16



#elif defined BSW_START_SEC_VAR_SLOW_CLEARED_32
    #undef  BSW_START_SEC_VAR_SLOW_CLEARED_32

#elif defined BSW_STOP_SEC_VAR_SLOW_CLEARED_32
    #undef BSW_STOP_SEC_VAR_SLOW_CLEARED_32



#elif defined BSW_START_SEC_VAR_SLOW_CLEARED_UNSPECIFIED
    #undef  BSW_START_SEC_VAR_SLOW_CLEARED_UNSPECIFIED

#elif defined BSW_STOP_SEC_VAR_SLOW_CLEARED_UNSPECIFIED
    #undef BSW_STOP_SEC_VAR_SLOW_CLEARED_UNSPECIFIED



#elif defined BSW_START_SEC_VAR_SLOW_POWER_ON_CLEARED_BOOLEAN
    #undef  BSW_START_SEC_VAR_SLOW_POWER_ON_CLEARED_BOOLEAN

#elif defined BSW_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_BOOLEAN
    #undef BSW_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_BOOLEAN



#elif defined BSW_START_SEC_VAR_SLOW_POWER_ON_CLEARED_8
    #undef  BSW_START_SEC_VAR_SLOW_POWER_ON_CLEARED_8

#elif defined BSW_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_8
    #undef BSW_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_8



#elif defined BSW_START_SEC_VAR_SLOW_POWER_ON_CLEARED_16
    #undef  BSW_START_SEC_VAR_SLOW_POWER_ON_CLEARED_16

#elif defined BSW_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_16
    #undef BSW_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_16



#elif defined BSW_START_SEC_VAR_SLOW_POWER_ON_CLEARED_32
    #undef  BSW_START_SEC_VAR_SLOW_POWER_ON_CLEARED_32

#elif defined BSW_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_32
    #undef BSW_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_32



#elif defined BSW_START_SEC_VAR_SLOW_POWER_ON_CLEARED_UNSPECIFIED
    #undef  BSW_START_SEC_VAR_SLOW_POWER_ON_CLEARED_UNSPECIFIED

#elif defined BSW_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_UNSPECIFIED
    #undef BSW_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_UNSPECIFIED



#elif defined BSW_START_SEC_VAR_SLOW_INIT_BOOLEAN
    #undef  BSW_START_SEC_VAR_SLOW_INIT_BOOLEAN

#elif defined BSW_STOP_SEC_VAR_SLOW_INIT_BOOLEAN
    #undef BSW_STOP_SEC_VAR_SLOW_INIT_BOOLEAN



#elif defined BSW_START_SEC_VAR_SLOW_INIT_8
    #undef  BSW_START_SEC_VAR_SLOW_INIT_8

#elif defined BSW_STOP_SEC_VAR_SLOW_INIT_8
    #undef BSW_STOP_SEC_VAR_SLOW_INIT_8



#elif defined BSW_START_SEC_VAR_SLOW_INIT_16
    #undef  BSW_START_SEC_VAR_SLOW_INIT_16

#elif defined BSW_STOP_SEC_VAR_SLOW_INIT_16
    #undef BSW_STOP_SEC_VAR_SLOW_INIT_16



#elif defined BSW_START_SEC_VAR_SLOW_INIT_32
    #undef  BSW_START_SEC_VAR_SLOW_INIT_32

#elif defined BSW_STOP_SEC_VAR_SLOW_INIT_32
    #undef BSW_STOP_SEC_VAR_SLOW_INIT_32



#elif defined BSW_START_SEC_VAR_SLOW_INIT_UNSPECIFIED
    #undef  BSW_START_SEC_VAR_SLOW_INIT_UNSPECIFIED

#elif defined BSW_STOP_SEC_VAR_SLOW_INIT_UNSPECIFIED
    #undef BSW_STOP_SEC_VAR_SLOW_INIT_UNSPECIFIED



#elif defined BSW_START_SEC_VAR_SLOW_POWER_ON_INIT_BOOLEAN
    #undef  BSW_START_SEC_VAR_SLOW_POWER_ON_INIT_BOOLEAN

#elif defined BSW_STOP_SEC_VAR_SLOW_POWER_ON_INIT_BOOLEAN
    #undef BSW_STOP_SEC_VAR_SLOW_POWER_ON_INIT_BOOLEAN



#elif defined BSW_START_SEC_VAR_SLOW_POWER_ON_INIT_8
    #undef  BSW_START_SEC_VAR_SLOW_POWER_ON_INIT_8

#elif defined BSW_STOP_SEC_VAR_SLOW_POWER_ON_INIT_8
    #undef BSW_STOP_SEC_VAR_SLOW_POWER_ON_INIT_8



#elif defined BSW_START_SEC_VAR_SLOW_POWER_ON_INIT_16
    #undef  BSW_START_SEC_VAR_SLOW_POWER_ON_INIT_16

#elif defined BSW_STOP_SEC_VAR_SLOW_POWER_ON_INIT_16
    #undef BSW_STOP_SEC_VAR_SLOW_POWER_ON_INIT_16



#elif defined BSW_START_SEC_VAR_SLOW_POWER_ON_INIT_32
    #undef  BSW_START_SEC_VAR_SLOW_POWER_ON_INIT_32

#elif defined BSW_STOP_SEC_VAR_SLOW_POWER_ON_INIT_32
    #undef BSW_STOP_SEC_VAR_SLOW_POWER_ON_INIT_32



#elif defined BSW_START_SEC_VAR_SLOW_POWER_ON_INIT_UNSPECIFIED
    #undef  BSW_START_SEC_VAR_SLOW_POWER_ON_INIT_UNSPECIFIED

#elif defined BSW_STOP_SEC_VAR_SLOW_POWER_ON_INIT_UNSPECIFIED
    #undef BSW_STOP_SEC_VAR_SLOW_POWER_ON_INIT_UNSPECIFIED



#elif defined BSW_START_SEC_INTERNAL_VAR_NO_INIT_BOOLEAN
    #undef  BSW_START_SEC_INTERNAL_VAR_NO_INIT_BOOLEAN
    /* NOTE: As per BSW coding guidelines the init policy NO_INIT shall not be used. */

#elif defined BSW_STOP_SEC_INTERNAL_VAR_NO_INIT_BOOLEAN
    #undef BSW_STOP_SEC_INTERNAL_VAR_NO_INIT_BOOLEAN



#elif defined BSW_START_SEC_INTERNAL_VAR_NO_INIT_8
    #undef  BSW_START_SEC_INTERNAL_VAR_NO_INIT_8
    /* NOTE: As per BSW coding guidelines the init policy NO_INIT shall not be used. */

#elif defined BSW_STOP_SEC_INTERNAL_VAR_NO_INIT_8
    #undef BSW_STOP_SEC_INTERNAL_VAR_NO_INIT_8



#elif defined BSW_START_SEC_INTERNAL_VAR_NO_INIT_16
    #undef  BSW_START_SEC_INTERNAL_VAR_NO_INIT_16
    /* NOTE: As per BSW coding guidelines the init policy NO_INIT shall not be used. */

#elif defined BSW_STOP_SEC_INTERNAL_VAR_NO_INIT_16
    #undef BSW_STOP_SEC_INTERNAL_VAR_NO_INIT_16



#elif defined BSW_START_SEC_INTERNAL_VAR_NO_INIT_32
    #undef  BSW_START_SEC_INTERNAL_VAR_NO_INIT_32
    /* NOTE: As per BSW coding guidelines the init policy NO_INIT shall not be used. */

#elif defined BSW_STOP_SEC_INTERNAL_VAR_NO_INIT_32
    #undef BSW_STOP_SEC_INTERNAL_VAR_NO_INIT_32



#elif defined BSW_START_SEC_INTERNAL_VAR_NO_INIT_UNSPECIFIED
    #undef  BSW_START_SEC_INTERNAL_VAR_NO_INIT_UNSPECIFIED
    /* NOTE: As per BSW coding guidelines the init policy NO_INIT shall not be used. */

#elif defined BSW_STOP_SEC_INTERNAL_VAR_NO_INIT_UNSPECIFIED
    #undef BSW_STOP_SEC_INTERNAL_VAR_NO_INIT_UNSPECIFIED



#elif defined BSW_START_SEC_INTERNAL_VAR_CLEARED_BOOLEAN
    #undef  BSW_START_SEC_INTERNAL_VAR_CLEARED_BOOLEAN

#elif defined BSW_STOP_SEC_INTERNAL_VAR_CLEARED_BOOLEAN
    #undef BSW_STOP_SEC_INTERNAL_VAR_CLEARED_BOOLEAN



#elif defined BSW_START_SEC_INTERNAL_VAR_CLEARED_8
    #undef  BSW_START_SEC_INTERNAL_VAR_CLEARED_8

#elif defined BSW_STOP_SEC_INTERNAL_VAR_CLEARED_8
    #undef BSW_STOP_SEC_INTERNAL_VAR_CLEARED_8



#elif defined BSW_START_SEC_INTERNAL_VAR_CLEARED_16
    #undef  BSW_START_SEC_INTERNAL_VAR_CLEARED_16

#elif defined BSW_STOP_SEC_INTERNAL_VAR_CLEARED_16
    #undef BSW_STOP_SEC_INTERNAL_VAR_CLEARED_16



#elif defined BSW_START_SEC_INTERNAL_VAR_CLEARED_32
    #undef  BSW_START_SEC_INTERNAL_VAR_CLEARED_32

#elif defined BSW_STOP_SEC_INTERNAL_VAR_CLEARED_32
    #undef BSW_STOP_SEC_INTERNAL_VAR_CLEARED_32



#elif defined BSW_START_SEC_INTERNAL_VAR_CLEARED_UNSPECIFIED
    #undef  BSW_START_SEC_INTERNAL_VAR_CLEARED_UNSPECIFIED

#elif defined BSW_STOP_SEC_INTERNAL_VAR_CLEARED_UNSPECIFIED
    #undef BSW_STOP_SEC_INTERNAL_VAR_CLEARED_UNSPECIFIED



#elif defined BSW_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_BOOLEAN
    #undef  BSW_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_BOOLEAN

#elif defined BSW_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_BOOLEAN
    #undef BSW_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_BOOLEAN



#elif defined BSW_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_8
    #undef  BSW_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_8

#elif defined BSW_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_8
    #undef BSW_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_8



#elif defined BSW_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_16
    #undef  BSW_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_16

#elif defined BSW_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_16
    #undef BSW_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_16



#elif defined BSW_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_32
    #undef  BSW_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_32

#elif defined BSW_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_32
    #undef BSW_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_32



#elif defined BSW_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_UNSPECIFIED
    #undef  BSW_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_UNSPECIFIED

#elif defined BSW_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_UNSPECIFIED
    #undef BSW_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_UNSPECIFIED



#elif defined BSW_START_SEC_INTERNAL_VAR_INIT_BOOLEAN
    #undef  BSW_START_SEC_INTERNAL_VAR_INIT_BOOLEAN

#elif defined BSW_STOP_SEC_INTERNAL_VAR_INIT_BOOLEAN
    #undef BSW_STOP_SEC_INTERNAL_VAR_INIT_BOOLEAN



#elif defined BSW_START_SEC_INTERNAL_VAR_INIT_8
    #undef  BSW_START_SEC_INTERNAL_VAR_INIT_8

#elif defined BSW_STOP_SEC_INTERNAL_VAR_INIT_8
    #undef BSW_STOP_SEC_INTERNAL_VAR_INIT_8



#elif defined BSW_START_SEC_INTERNAL_VAR_INIT_16
    #undef  BSW_START_SEC_INTERNAL_VAR_INIT_16

#elif defined BSW_STOP_SEC_INTERNAL_VAR_INIT_16
    #undef BSW_STOP_SEC_INTERNAL_VAR_INIT_16



#elif defined BSW_START_SEC_INTERNAL_VAR_INIT_32
    #undef  BSW_START_SEC_INTERNAL_VAR_INIT_32

#elif defined BSW_STOP_SEC_INTERNAL_VAR_INIT_32
    #undef BSW_STOP_SEC_INTERNAL_VAR_INIT_32



#elif defined BSW_START_SEC_INTERNAL_VAR_INIT_UNSPECIFIED
    #undef  BSW_START_SEC_INTERNAL_VAR_INIT_UNSPECIFIED

#elif defined BSW_STOP_SEC_INTERNAL_VAR_INIT_UNSPECIFIED
    #undef BSW_STOP_SEC_INTERNAL_VAR_INIT_UNSPECIFIED



#elif defined BSW_START_SEC_INTERNAL_VAR_POWER_ON_INIT_BOOLEAN
    #undef  BSW_START_SEC_INTERNAL_VAR_POWER_ON_INIT_BOOLEAN

#elif defined BSW_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_BOOLEAN
    #undef BSW_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_BOOLEAN



#elif defined BSW_START_SEC_INTERNAL_VAR_POWER_ON_INIT_8
    #undef  BSW_START_SEC_INTERNAL_VAR_POWER_ON_INIT_8

#elif defined BSW_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_8
    #undef BSW_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_8



#elif defined BSW_START_SEC_INTERNAL_VAR_POWER_ON_INIT_16
    #undef  BSW_START_SEC_INTERNAL_VAR_POWER_ON_INIT_16

#elif defined BSW_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_16
    #undef BSW_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_16



#elif defined BSW_START_SEC_INTERNAL_VAR_POWER_ON_INIT_32
    #undef  BSW_START_SEC_INTERNAL_VAR_POWER_ON_INIT_32

#elif defined BSW_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_32
    #undef BSW_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_32



#elif defined BSW_START_SEC_INTERNAL_VAR_POWER_ON_INIT_UNSPECIFIED
    #undef  BSW_START_SEC_INTERNAL_VAR_POWER_ON_INIT_UNSPECIFIED

#elif defined BSW_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_UNSPECIFIED
    #undef BSW_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_UNSPECIFIED



#elif defined BSW_START_SEC_VAR_SAVED_ZONE_BOOLEAN
    #undef  BSW_START_SEC_VAR_SAVED_ZONE_BOOLEAN

#elif defined BSW_STOP_SEC_VAR_SAVED_ZONE_BOOLEAN
    #undef BSW_STOP_SEC_VAR_SAVED_ZONE_BOOLEAN



#elif defined BSW_START_SEC_VAR_SAVED_ZONE_8
    #undef  BSW_START_SEC_VAR_SAVED_ZONE_8

#elif defined BSW_STOP_SEC_VAR_SAVED_ZONE_8
    #undef BSW_STOP_SEC_VAR_SAVED_ZONE_8



#elif defined BSW_START_SEC_VAR_SAVED_ZONE_16
    #undef  BSW_START_SEC_VAR_SAVED_ZONE_16

#elif defined BSW_STOP_SEC_VAR_SAVED_ZONE_16
    #undef BSW_STOP_SEC_VAR_SAVED_ZONE_16



#elif defined BSW_START_SEC_VAR_SAVED_ZONE_32
    #undef  BSW_START_SEC_VAR_SAVED_ZONE_32

#elif defined BSW_STOP_SEC_VAR_SAVED_ZONE_32
    #undef BSW_STOP_SEC_VAR_SAVED_ZONE_32



#elif defined BSW_START_SEC_VAR_SAVED_ZONE_UNSPECIFIED
    #undef  BSW_START_SEC_VAR_SAVED_ZONE_UNSPECIFIED

#elif defined BSW_STOP_SEC_VAR_SAVED_ZONE_UNSPECIFIED
    #undef BSW_STOP_SEC_VAR_SAVED_ZONE_UNSPECIFIED



#elif defined BSW_START_SEC_DEFAULT_RAM0_CLEARED_UNSPECIFIED
    #undef BSW_START_SEC_DEFAULT_RAM0_CLEARED_UNSPECIFIED
#elif defined BSW_STOP_SEC_DEFAULT_RAM0_CLEARED_UNSPECIFIED
    #undef BSW_STOP_SEC_DEFAULT_RAM0_CLEARED_UNSPECIFIED

#elif defined BSW_START_SEC_DEFAULT_RAM0_INIT_UNSPECIFIED
    #undef BSW_START_SEC_DEFAULT_RAM0_INIT_UNSPECIFIED
#elif defined BSW_STOP_SEC_DEFAULT_RAM0_INIT_UNSPECIFIED
    #undef BSW_STOP_SEC_DEFAULT_RAM0_INIT_UNSPECIFIED


#elif defined BSW_START_SEC_DEFAULT_RAM0_CLEARED_8
    #undef BSW_START_SEC_DEFAULT_RAM0_CLEARED_8
#elif defined BSW_STOP_SEC_DEFAULT_RAM0_CLEARED_8
    #undef BSW_STOP_SEC_DEFAULT_RAM0_CLEARED_8

#elif defined BSW_START_SEC_DEFAULT_RAM0_INIT_8
    #undef BSW_START_SEC_DEFAULT_RAM0_INIT_8
#elif defined BSW_STOP_SEC_DEFAULT_RAM0_INIT_8
    #undef BSW_STOP_SEC_DEFAULT_RAM0_INIT_8


#elif defined BSW_START_SEC_DEFAULT_RAM0_CLEARED_16
    #undef BSW_START_SEC_DEFAULT_RAM0_CLEARED_16
#elif defined BSW_STOP_SEC_DEFAULT_RAM0_CLEARED_16
    #undef BSW_STOP_SEC_DEFAULT_RAM0_CLEARED_16

#elif defined BSW_START_SEC_DEFAULT_RAM0_INIT_16
    #undef BSW_START_SEC_DEFAULT_RAM0_INIT_16
#elif defined BSW_STOP_SEC_DEFAULT_RAM0_INIT_16
    #undef BSW_STOP_SEC_DEFAULT_RAM0_INIT_16

#elif defined BSW_START_SEC_DEFAULT_RAM0_CLEARED_32
    #undef BSW_START_SEC_DEFAULT_RAM0_CLEARED_32
#elif defined BSW_STOP_SEC_DEFAULT_RAM0_CLEARED_32
    #undef BSW_STOP_SEC_DEFAULT_RAM0_CLEARED_32

#elif defined BSW_START_SEC_DEFAULT_RAM0_INIT_32
    #undef BSW_START_SEC_DEFAULT_RAM0_INIT_32
#elif defined BSW_STOP_SEC_DEFAULT_RAM0_INIT_32
    #undef BSW_STOP_SEC_DEFAULT_RAM0_INIT_32

/* CONSTANTS */
#elif defined BSW_START_SEC_DEFAULT_CONST_UNSPECIFIED
    #undef BSW_START_SEC_DEFAULT_CONST_UNSPECIFIED
#elif defined BSW_STOP_SEC_DEFAULT_CONST_UNSPECIFIED
    #undef BSW_STOP_SEC_DEFAULT_CONST_UNSPECIFIED


#elif defined BSW_START_SEC_DEFAULT_CONST_8
    #undef BSW_START_SEC_DEFAULT_CONST_8
#elif defined BSW_STOP_SEC_DEFAULT_CONST_8
    #undef BSW_STOP_SEC_DEFAULT_CONST_8


#elif defined BSW_START_SEC_DEFAULT_CONST_16
    #undef BSW_START_SEC_DEFAULT_CONST_16
#elif defined BSW_STOP_SEC_DEFAULT_CONST_16
    #undef BSW_STOP_SEC_DEFAULT_CONST_16


#elif defined BSW_START_SEC_DEFAULT_CONST_32
    #undef BSW_START_SEC_DEFAULT_CONST_32
#elif defined BSW_STOP_SEC_DEFAULT_CONST_32
    #undef BSW_STOP_SEC_DEFAULT_CONST_32


#elif defined BSW_START_SEC_CONST_BOOLEAN
    #undef  BSW_START_SEC_CONST_BOOLEAN

#elif defined BSW_STOP_SEC_CONST_BOOLEAN
    #undef BSW_STOP_SEC_CONST_BOOLEAN



#elif defined BSW_START_SEC_CONST_8
    #undef  BSW_START_SEC_CONST_8

#elif defined BSW_STOP_SEC_CONST_8
    #undef BSW_STOP_SEC_CONST_8



#elif defined BSW_START_SEC_CONST_16
    #undef  BSW_START_SEC_CONST_16

#elif defined BSW_STOP_SEC_CONST_16
    #undef BSW_STOP_SEC_CONST_16



#elif defined BSW_START_SEC_CONST_32
    #undef  BSW_START_SEC_CONST_32

#elif defined BSW_STOP_SEC_CONST_32
    #undef BSW_STOP_SEC_CONST_32



#elif defined BSW_START_SEC_CONST_UNSPECIFIED
    #undef  BSW_START_SEC_CONST_UNSPECIFIED

#elif defined BSW_STOP_SEC_CONST_UNSPECIFIED
    #undef BSW_STOP_SEC_CONST_UNSPECIFIED



#elif defined BSW_START_SEC_CONST_FAST_BOOLEAN
    #undef  BSW_START_SEC_CONST_FAST_BOOLEAN

#elif defined BSW_STOP_SEC_CONST_FAST_BOOLEAN
    #undef BSW_STOP_SEC_CONST_FAST_BOOLEAN



#elif defined BSW_START_SEC_CONST_FAST_8
    #undef  BSW_START_SEC_CONST_FAST_8

#elif defined BSW_STOP_SEC_CONST_FAST_8
    #undef BSW_STOP_SEC_CONST_FAST_8



#elif defined BSW_START_SEC_CONST_FAST_16
    #undef  BSW_START_SEC_CONST_FAST_16

#elif defined BSW_STOP_SEC_CONST_FAST_16
    #undef BSW_STOP_SEC_CONST_FAST_16



#elif defined BSW_START_SEC_CONST_FAST_32
    #undef  BSW_START_SEC_CONST_FAST_32

#elif defined BSW_STOP_SEC_CONST_FAST_32
    #undef BSW_STOP_SEC_CONST_FAST_32



#elif defined BSW_START_SEC_CONST_FAST_UNSPECIFIED
    #undef  BSW_START_SEC_CONST_FAST_UNSPECIFIED

#elif defined BSW_STOP_SEC_CONST_FAST_UNSPECIFIED
    #undef BSW_STOP_SEC_CONST_FAST_UNSPECIFIED



#elif defined BSW_START_SEC_CONST_SLOW_BOOLEAN
    #undef  BSW_START_SEC_CONST_SLOW_BOOLEAN

#elif defined BSW_STOP_SEC_CONST_SLOW_BOOLEAN
    #undef BSW_STOP_SEC_CONST_SLOW_BOOLEAN



#elif defined BSW_START_SEC_CONST_SLOW_8
    #undef  BSW_START_SEC_CONST_SLOW_8

#elif defined BSW_STOP_SEC_CONST_SLOW_8
    #undef BSW_STOP_SEC_CONST_SLOW_8



#elif defined BSW_START_SEC_CONST_SLOW_16
    #undef  BSW_START_SEC_CONST_SLOW_16

#elif defined BSW_STOP_SEC_CONST_SLOW_16
    #undef BSW_STOP_SEC_CONST_SLOW_16



#elif defined BSW_START_SEC_CONST_SLOW_32
    #undef  BSW_START_SEC_CONST_SLOW_32

#elif defined BSW_STOP_SEC_CONST_SLOW_32
    #undef BSW_STOP_SEC_CONST_SLOW_32



#elif defined BSW_START_SEC_CONST_SLOW_UNSPECIFIED
    #undef  BSW_START_SEC_CONST_SLOW_UNSPECIFIED

#elif defined BSW_STOP_SEC_CONST_SLOW_UNSPECIFIED
    #undef BSW_STOP_SEC_CONST_SLOW_UNSPECIFIED



#elif defined BSW_START_SEC_CALIB_BOOLEAN
    #undef  BSW_START_SEC_CALIB_BOOLEAN

#elif defined BSW_STOP_SEC_CALIB_BOOLEAN
    #undef BSW_STOP_SEC_CALIB_BOOLEAN



#elif defined BSW_START_SEC_CALIB_8
    #undef  BSW_START_SEC_CALIB_8

#elif defined BSW_STOP_SEC_CALIB_8
    #undef BSW_STOP_SEC_CALIB_8



#elif defined BSW_START_SEC_CALIB_16
    #undef  BSW_START_SEC_CALIB_16

#elif defined BSW_STOP_SEC_CALIB_16
    #undef BSW_STOP_SEC_CALIB_16



#elif defined BSW_START_SEC_CALIB_32
    #undef  BSW_START_SEC_CALIB_32

#elif defined BSW_STOP_SEC_CALIB_32
    #undef BSW_STOP_SEC_CALIB_32



#elif defined BSW_START_SEC_CALIB_UNSPECIFIED
    #undef  BSW_START_SEC_CALIB_UNSPECIFIED

#elif defined BSW_STOP_SEC_CALIB_UNSPECIFIED
    #undef BSW_STOP_SEC_CALIB_UNSPECIFIED



#elif defined BSW_START_SEC_CALIB_FAST_BOOLEAN
    #undef  BSW_START_SEC_CALIB_FAST_BOOLEAN

#elif defined BSW_STOP_SEC_CALIB_FAST_BOOLEAN
    #undef BSW_STOP_SEC_CALIB_FAST_BOOLEAN



#elif defined BSW_START_SEC_CALIB_FAST_8
    #undef  BSW_START_SEC_CALIB_FAST_8

#elif defined BSW_STOP_SEC_CALIB_FAST_8
    #undef BSW_STOP_SEC_CALIB_FAST_8



#elif defined BSW_START_SEC_CALIB_FAST_16
    #undef  BSW_START_SEC_CALIB_FAST_16

#elif defined BSW_STOP_SEC_CALIB_FAST_16
    #undef BSW_STOP_SEC_CALIB_FAST_16



#elif defined BSW_START_SEC_CALIB_FAST_32
    #undef  BSW_START_SEC_CALIB_FAST_32

#elif defined BSW_STOP_SEC_CALIB_FAST_32
    #undef BSW_STOP_SEC_CALIB_FAST_32



#elif defined BSW_START_SEC_CALIB_FAST_UNSPECIFIED
    #undef  BSW_START_SEC_CALIB_FAST_UNSPECIFIED

#elif defined BSW_STOP_SEC_CALIB_FAST_UNSPECIFIED
    #undef BSW_STOP_SEC_CALIB_FAST_UNSPECIFIED



#elif defined BSW_START_SEC_CALIB_SLOW_BOOLEAN
    #undef  BSW_START_SEC_CALIB_SLOW_BOOLEAN

#elif defined BSW_STOP_SEC_CALIB_SLOW_BOOLEAN
    #undef BSW_STOP_SEC_CALIB_SLOW_BOOLEAN



#elif defined BSW_START_SEC_CALIB_SLOW_8
    #undef  BSW_START_SEC_CALIB_SLOW_8

#elif defined BSW_STOP_SEC_CALIB_SLOW_8
    #undef BSW_STOP_SEC_CALIB_SLOW_8



#elif defined BSW_START_SEC_CALIB_SLOW_16
    #undef  BSW_START_SEC_CALIB_SLOW_16

#elif defined BSW_STOP_SEC_CALIB_SLOW_16
    #undef BSW_STOP_SEC_CALIB_SLOW_16



#elif defined BSW_START_SEC_CALIB_SLOW_32
    #undef  BSW_START_SEC_CALIB_SLOW_32

#elif defined BSW_STOP_SEC_CALIB_SLOW_32
    #undef BSW_STOP_SEC_CALIB_SLOW_32



#elif defined BSW_START_SEC_CALIB_SLOW_UNSPECIFIED
    #undef  BSW_START_SEC_CALIB_SLOW_UNSPECIFIED

#elif defined BSW_STOP_SEC_CALIB_SLOW_UNSPECIFIED
    #undef BSW_STOP_SEC_CALIB_SLOW_UNSPECIFIED



#elif defined BSW_START_SEC_CARTO_BOOLEAN
    #undef  BSW_START_SEC_CARTO_BOOLEAN

#elif defined BSW_STOP_SEC_CARTO_BOOLEAN
    #undef BSW_STOP_SEC_CARTO_BOOLEAN



#elif defined BSW_START_SEC_CARTO_8
    #undef  BSW_START_SEC_CARTO_8

#elif defined BSW_STOP_SEC_CARTO_8
    #undef BSW_STOP_SEC_CARTO_8



#elif defined BSW_START_SEC_CARTO_16
    #undef  BSW_START_SEC_CARTO_16

#elif defined BSW_STOP_SEC_CARTO_16
    #undef BSW_STOP_SEC_CARTO_16



#elif defined BSW_START_SEC_CARTO_32
    #undef  BSW_START_SEC_CARTO_32

#elif defined BSW_STOP_SEC_CARTO_32
    #undef BSW_STOP_SEC_CARTO_32



#elif defined BSW_START_SEC_CARTO_UNSPECIFIED
    #undef  BSW_START_SEC_CARTO_UNSPECIFIED

#elif defined BSW_STOP_SEC_CARTO_UNSPECIFIED
    #undef BSW_STOP_SEC_CARTO_UNSPECIFIED



#elif defined BSW_START_SEC_CONFIG_DATA_BOOLEAN
    #undef  BSW_START_SEC_CONFIG_DATA_BOOLEAN

#elif defined BSW_STOP_SEC_CONFIG_DATA_BOOLEAN
    #undef BSW_STOP_SEC_CONFIG_DATA_BOOLEAN



#elif defined BSW_START_SEC_CONFIG_DATA_8
    #undef  BSW_START_SEC_CONFIG_DATA_8

#elif defined BSW_STOP_SEC_CONFIG_DATA_8
    #undef BSW_STOP_SEC_CONFIG_DATA_8



#elif defined BSW_START_SEC_CONFIG_DATA_16
    #undef  BSW_START_SEC_CONFIG_DATA_16

#elif defined BSW_STOP_SEC_CONFIG_DATA_16
    #undef BSW_STOP_SEC_CONFIG_DATA_16



#elif defined BSW_START_SEC_CONFIG_DATA_32
    #undef  BSW_START_SEC_CONFIG_DATA_32

#elif defined BSW_STOP_SEC_CONFIG_DATA_32
    #undef BSW_STOP_SEC_CONFIG_DATA_32



#elif defined BSW_START_SEC_CONFIG_DATA_UNSPECIFIED
    #undef  BSW_START_SEC_CONFIG_DATA_UNSPECIFIED

#elif defined BSW_STOP_SEC_CONFIG_DATA_UNSPECIFIED
    #undef BSW_STOP_SEC_CONFIG_DATA_UNSPECIFIED



#elif defined BSW_START_SEC_CONFIG_DATA_FAST_BOOLEAN
    #undef  BSW_START_SEC_CONFIG_DATA_FAST_BOOLEAN

#elif defined BSW_STOP_SEC_CONFIG_DATA_FAST_BOOLEAN
    #undef BSW_STOP_SEC_CONFIG_DATA_FAST_BOOLEAN



#elif defined BSW_START_SEC_CONFIG_DATA_FAST_8
    #undef  BSW_START_SEC_CONFIG_DATA_FAST_8

#elif defined BSW_STOP_SEC_CONFIG_DATA_FAST_8
    #undef BSW_STOP_SEC_CONFIG_DATA_FAST_8



#elif defined BSW_START_SEC_CONFIG_DATA_FAST_16
    #undef  BSW_START_SEC_CONFIG_DATA_FAST_16

#elif defined BSW_STOP_SEC_CONFIG_DATA_FAST_16
    #undef BSW_STOP_SEC_CONFIG_DATA_FAST_16



#elif defined BSW_START_SEC_CONFIG_DATA_FAST_32
    #undef  BSW_START_SEC_CONFIG_DATA_FAST_32

#elif defined BSW_STOP_SEC_CONFIG_DATA_FAST_32
    #undef BSW_STOP_SEC_CONFIG_DATA_FAST_32



#elif defined BSW_START_SEC_CONFIG_DATA_FAST_UNSPECIFIED
    #undef  BSW_START_SEC_CONFIG_DATA_FAST_UNSPECIFIED

#elif defined BSW_STOP_SEC_CONFIG_DATA_FAST_UNSPECIFIED
    #undef BSW_STOP_SEC_CONFIG_DATA_FAST_UNSPECIFIED



#elif defined BSW_START_SEC_CONFIG_DATA_SLOW_BOOLEAN
    #undef  BSW_START_SEC_CONFIG_DATA_SLOW_BOOLEAN

#elif defined BSW_STOP_SEC_CONFIG_DATA_SLOW_BOOLEAN
    #undef BSW_STOP_SEC_CONFIG_DATA_SLOW_BOOLEAN



#elif defined BSW_START_SEC_CONFIG_DATA_SLOW_8
    #undef  BSW_START_SEC_CONFIG_DATA_SLOW_8

#elif defined BSW_STOP_SEC_CONFIG_DATA_SLOW_8
    #undef BSW_STOP_SEC_CONFIG_DATA_SLOW_8



#elif defined BSW_START_SEC_CONFIG_DATA_SLOW_16
    #undef  BSW_START_SEC_CONFIG_DATA_SLOW_16

#elif defined BSW_STOP_SEC_CONFIG_DATA_SLOW_16
    #undef BSW_STOP_SEC_CONFIG_DATA_SLOW_16



#elif defined BSW_START_SEC_CONFIG_DATA_SLOW_32
    #undef  BSW_START_SEC_CONFIG_DATA_SLOW_32

#elif defined BSW_STOP_SEC_CONFIG_DATA_SLOW_32
    #undef BSW_STOP_SEC_CONFIG_DATA_SLOW_32



#elif defined BSW_START_SEC_CONFIG_DATA_SLOW_UNSPECIFIED
    #undef  BSW_START_SEC_CONFIG_DATA_SLOW_UNSPECIFIED

#elif defined BSW_STOP_SEC_CONFIG_DATA_SLOW_UNSPECIFIED
    #undef BSW_STOP_SEC_CONFIG_DATA_SLOW_UNSPECIFIED



#elif defined BSW_START_SEC_CONFIG_DATA_POSTBUILD_HEADER
    #undef  BSW_START_SEC_CONFIG_DATA_POSTBUILD_HEADER

#elif defined BSW_STOP_SEC_CONFIG_DATA_POSTBUILD_HEADER
    #undef BSW_STOP_SEC_CONFIG_DATA_POSTBUILD_HEADER



#elif defined BSW_START_SEC_CONFIG_DATA_POSTBUILD_BOOLEAN
    #undef  BSW_START_SEC_CONFIG_DATA_POSTBUILD_BOOLEAN

#elif defined BSW_STOP_SEC_CONFIG_DATA_POSTBUILD_BOOLEAN
    #undef BSW_STOP_SEC_CONFIG_DATA_POSTBUILD_BOOLEAN



#elif defined BSW_START_SEC_CONFIG_DATA_POSTBUILD_8
    #undef  BSW_START_SEC_CONFIG_DATA_POSTBUILD_8

#elif defined BSW_STOP_SEC_CONFIG_DATA_POSTBUILD_8
    #undef BSW_STOP_SEC_CONFIG_DATA_POSTBUILD_8



#elif defined BSW_START_SEC_CONFIG_DATA_POSTBUILD_16
    #undef  BSW_START_SEC_CONFIG_DATA_POSTBUILD_16

#elif defined BSW_STOP_SEC_CONFIG_DATA_POSTBUILD_16
    #undef BSW_STOP_SEC_CONFIG_DATA_POSTBUILD_16



#elif defined BSW_START_SEC_CONFIG_DATA_POSTBUILD_32
    #undef  BSW_START_SEC_CONFIG_DATA_POSTBUILD_32

#elif defined BSW_STOP_SEC_CONFIG_DATA_POSTBUILD_32
    #undef BSW_STOP_SEC_CONFIG_DATA_POSTBUILD_32



#elif defined BSW_START_SEC_CONFIG_DATA_POSTBUILD_UNSPECIFIED
    #undef  BSW_START_SEC_CONFIG_DATA_POSTBUILD_UNSPECIFIED

#elif defined BSW_STOP_SEC_CONFIG_DATA_POSTBUILD_UNSPECIFIED
    #undef BSW_STOP_SEC_CONFIG_DATA_POSTBUILD_UNSPECIFIED



#elif defined BSW_START_SEC_VAR_SAVED_RECOVERY_ZONE
    #undef  BSW_START_SEC_VAR_SAVED_RECOVERY_ZONE

#elif defined BSW_STOP_SEC_VAR_SAVED_RECOVERY_ZONE
    #undef BSW_STOP_SEC_VAR_SAVED_RECOVERY_ZONE


#elif defined BSW_START_SEC_DEFAULT_RESET_SAFE_RAM0_32
    #undef BSW_START_SEC_DEFAULT_RESET_SAFE_RAM0_32
#elif defined BSW_STOP_SEC_DEFAULT_RESET_SAFE_RAM0_32
    #undef BSW_STOP_SEC_DEFAULT_RESET_SAFE_RAM0_32


#elif defined BSW_START_SEC_DEFAULT_RESET_SAFE_RAM0_UNSPECIFIED
    #undef BSW_START_SEC_DEFAULT_RESET_SAFE_RAM0_UNSPECIFIED
#elif defined BSW_STOP_SEC_DEFAULT_RESET_SAFE_RAM0_UNSPECIFIED
    #undef BSW_STOP_SEC_DEFAULT_RESET_SAFE_RAM0_UNSPECIFIED


#elif defined BSW_START_SEC_SPRAM_CODE
    #undef BSW_START_SEC_SPRAM_CODE
#elif defined BSW_STOP_SEC_SPRAM_CODE
    #undef BSW_STOP_SEC_SPRAM_CODE


/* CODE */
#elif defined BSW_START_SEC_DEFAULT_CODE
    #undef BSW_START_SEC_DEFAULT_CODE
#elif defined BSW_STOP_SEC_DEFAULT_CODE
    #undef BSW_STOP_SEC_DEFAULT_CODE

#elif defined BSW_START_SEC_CODE
    #undef  BSW_START_SEC_CODE

#elif defined BSW_STOP_SEC_CODE
    #undef BSW_STOP_SEC_CODE


#elif defined BSW_START_SEC_DEFAULT_CONST_32
    #undef BSW_START_SEC_DEFAULT_CONST_32
#elif defined BSW_STOP_SEC_DEFAULT_CONST_32
    #undef BSW_STOP_SEC_DEFAULT_CONST_32



#elif defined BSW_START_SEC_CODE_FAST
    #undef  BSW_START_SEC_CODE_FAST

#elif defined BSW_STOP_SEC_CODE_FAST
    #undef BSW_STOP_SEC_CODE_FAST



#elif defined BSW_START_SEC_CODE_SLOW
    #undef  BSW_START_SEC_CODE_SLOW

#elif defined BSW_STOP_SEC_CODE_SLOW
    #undef BSW_STOP_SEC_CODE_SLOW



#elif defined BSW_START_SEC_CODE_LIB
    #undef  BSW_START_SEC_CODE_LIB

#elif defined BSW_STOP_SEC_CODE_LIB
    #undef BSW_STOP_SEC_CODE_LIB


#elif defined BSW_START_SEC_SAVED_ZONE_8
    #undef  BSW_START_SEC_SAVED_ZONE_8

#elif defined BSW_STOP_SEC_SAVED_ZONE_8
    #undef BSW_STOP_SEC_SAVED_ZONE_8


/* USER DEFINED */

#elif defined BSW_START_SEC_SAVED_ZONE_8
    #undef  BSW_START_SEC_SAVED_ZONE_8

#elif defined BSW_STOP_SEC_SAVED_ZONE_8
    #undef BSW_STOP_SEC_SAVED_ZONE_8


#elif defined BSW_START_SEC_SAVED_ZONE_16
    #undef  BSW_START_SEC_SAVED_ZONE_16

#elif defined BSW_STOP_SEC_SAVED_ZONE_16
    #undef BSW_STOP_SEC_SAVED_ZONE_16


#elif defined BSW_START_SEC_SAVED_ZONE_32
    #undef  BSW_START_SEC_SAVED_ZONE_32

#elif defined BSW_STOP_SEC_SAVED_ZONE_32
    #undef BSW_STOP_SEC_SAVED_ZONE_32


#elif defined BSW_START_SEC_SAVED_ZONE_UNSPECIFIED
    #undef  BSW_START_SEC_SAVED_ZONE_UNSPECIFIED

#elif defined BSW_STOP_SEC_SAVED_ZONE_UNSPECIFIED
    #undef BSW_STOP_SEC_SAVED_ZONE_UNSPECIFIED

#elif defined BSW_START_SEC_CALLOUT_CODE
    #undef  BSW_START_SEC_CALLOUT_CODE

#elif defined BSW_STOP_SEC_CALLOUT_CODE
    #undef BSW_STOP_SEC_CALLOUT_CODE

#elif defined BSW_START_SEC_VAR_CLEARED_8_SECURED
    #undef  BSW_START_SEC_VAR_CLEARED_8_SECURED

#elif defined BSW_STOP_SEC_VAR_CLEARED_8_SECURED
    #undef BSW_STOP_SEC_VAR_CLEARED_8_SECURED

#elif defined BSW_START_SEC_VAR_CLEARED_SECURED_8
    #undef  BSW_START_SEC_VAR_CLEARED_SECURED_8

#elif defined BSW_STOP_SEC_VAR_CLEARED_SECURED_8
    #undef BSW_STOP_SEC_VAR_CLEARED_SECURED_8

#elif defined BSW_START_SEC_VAR_CLEARED_32_SECURED
    #undef  BSW_START_SEC_VAR_CLEARED_32_SECURED

#elif defined BSW_STOP_SEC_VAR_CLEARED_32_SECURED
    #undef BSW_STOP_SEC_VAR_CLEARED_32_SECURED

#elif defined BSW_START_SEC_VAR_CLEARED_SECURED_32
    #undef  BSW_START_SEC_VAR_CLEARED_SECURED_32

#elif defined BSW_STOP_SEC_VAR_CLEARED_SECURED_32
    #undef BSW_STOP_SEC_VAR_CLEARED_SECURED_32

#elif defined BSW_START_SEC_VAR_CLEARED_UNSPECIFIED_SECURED
    #undef  BSW_START_SEC_VAR_CLEARED_UNSPECIFIED_SECURED

#elif defined BSW_STOP_SEC_VAR_CLEARED_UNSPECIFIED_SECURED
    #undef BSW_STOP_SEC_VAR_CLEARED_UNSPECIFIED_SECURED

#elif defined BSW_START_SEC_VAR_CLEARED_SECURED_UNSPECIFIED
    #undef  BSW_START_SEC_VAR_CLEARED_SECURED_UNSPECIFIED

#elif defined BSW_STOP_SEC_VAR_CLEARED_SECURED_UNSPECIFIED
    #undef BSW_STOP_SEC_VAR_CLEARED_SECURED_UNSPECIFIED

#elif defined BSW_START_SEC_VAR_CLEARED_SECURED_CACHE_LINE_ALIGNED_UNSPECIFIED
    #undef  BSW_START_SEC_VAR_CLEARED_SECURED_CACHE_LINE_ALIGNED_UNSPECIFIED

#elif defined BSW_STOP_SEC_VAR_CLEARED_SECURED_CACHE_LINE_ALIGNED_UNSPECIFIED
    #undef BSW_STOP_SEC_VAR_CLEARED_SECURED_CACHE_LINE_ALIGNED_UNSPECIFIED

#else
    #error "Bsw_MemMap.h, memmap section unconfigured"
#endif
