/** @file     Rte_DataHandleType.h
  *
  * @brief    RTE DataElement type definitions
  *
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  *
  * @note     Generated by ETAS RTA-RTE
  * @note     Version 7.1.0 
  *
  * @date     Mon Nov 29 16:06:17 2021
  */

#ifndef RTE_DATA_HANDLE_TYPE_H
#define RTE_DATA_HANDLE_TYPE_H

#include "Rte_Type.h"
#include "Rte_Cfg.h"

typedef struct {
   uint16 value;
} Rte_DE_uint16;

typedef struct {
   uint8 value;
} Rte_DE_uint8;

typedef struct {
   Rte_DE_uint8  rbuf0;
   Rte_DE_uint16 sbuf1;
} Rte_TDB_OsTask_10ms;

typedef union {
   Rte_TDB_OsTask_10ms Rte_OsTask_10ms;
} Rte_ISA_1;

typedef struct {
   Rte_ISA_1 isa_1;
} Rte_ImplicitBufsType;


#endif /* !RTE_DATA_HANDLE_TYPE_H */
