/** @file     Rte_Cbk.h
  *
  * @brief    RTE generated callbacks
  *
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  *
  * @note     Generated by ETAS RTA-RTE
  * @note     Version 7.1.0 
  *
  * @date     Sun Nov 28 22:56:39 2021
  */

#ifndef RTE_CBK_H
#define RTE_CBK_H

/* ----- RTE Callback functions ----- */

FUNC(void, RTE_CODE) Rte_COMCbk_BMS_SubsymCodeFrameOrder2(void);

#endif /* !RTE_CBK_H */
